# Generated by Django 4.1.1 on 2022-09-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_category_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='feature',
        ),
        migrations.AddField(
            model_name='photo',
            name='feature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
