# Generated by Django 4.1.1 on 2022-09-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_remove_category_feature_photo_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='feature',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
